apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cli-manager-operator
spec:
  selector:
    matchLabels:
      name: openshift-cli-manager-operator
  endpoints:
    - port: https
      scheme: https
      interval: 30s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: cli-manager-operator-metrics.openshift-cli-manager-operator.svc
